### ISSUE TITLE
Is it possible to cache the result for different amounts of time?

### ISSUE THREAD

**Issue by m1dst** [proxykit/Recipes#1]
I have looked at the recipe for caching a response.

Is it possible to do some kind of conditional caching?

EG: Not all proxied URLs should be cached. (I'm using UseWhen)
Different cache durations per Url (UseWhen)

**Comment by damianh** [comment]
The caching recipe is based on [CacheCow](https://github.com/aliostad/CacheCow) which is entirely driven by the HTTP response headers from upstream servers. My first feeling is that if your reverese proxy is ignoring caching headers from upstream hosts then you should look at your upstream host configurtion.

If CacheCow is not configurable to what you are trying to do, then perphaps adding your own http handler to the pipeline that is executed _after_ CacheCow that allows adjusting of the response's caching headers (i.e. removing etag) _before_ CacheCow sees it might allow the response to pass through.
